swagger: "2.0"
info:
  version: 1.0.0
  title: tango-api
  description: Tango API
  termsOfService: http://swagger.io/terms/
  contact:
    name: Tango API Team
    email: diego.domingues16@gmail.com
    url: https://github.com/tango-crew/tango-api
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: tango-api.herokuapp.com
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      description: |
        Returns all system's users
      responses:
        200:
          description: user response
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      description: Creates a new User in the app. Duplicates are not allowed
      parameters:
        - name: user
          in: body
          description: User to add to the store
          required: true
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        200:
          description: user response
          schema:
            $ref: '#/definitions/User'
  /users/{id}:
    get:
      description: Returns a user based on a single ID
      operationId: find user by id
      parameters:
        - name: id
          in: path
          description: ID of user to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: user response
          schema:
            $ref: '#/definitions/User'
    delete:
      description: deletes a single pet based on the ID supplied
      operationId: deletePet
      parameters:
        - name: id
          in: path
          description: ID of pet to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: user deleted
definitions:
  User:
    type: object

    properties:
      id:
        type: integer
        description: Unique identifier representing a specific user.
      name:
        type: string
        description: User's name.
      email:
        type: string
        description: User's email.
      token:
        type: string
        description: Auth token.
      integration_id:
        type: integer
        description: An integration Id.
      birthday:
        type: string
        format: date
        description: User's birthday
      bio:
        type: string
        description: User's resumed bio.
  NewUser:
    required:
      - name
      - email
      - token
      - bio
    properties:
      name:
        type: string
      email:
        type: string
      token:
        type: string
      integration_id:
        type: integer
      birthday:
        type: string
        format: date
      bio:
        type: string